- src/index.html
> yasu's first test commit.Added company message in English.

- src/index.pug
- src/js/home.js
- src/mixin/video-mordal.pug
- src/scss/video-modal.scss
- 1枚目
- 「ビデオを見る」ボタンでビデオが再生されること
- 2枚目
- 文言に違和感が無いか
- 「登録する」ボタンでサブスクリプションページへ飛ぶこと
- 備考
- 改善点は山ほどあるのですが、ひとまずミニマムでございます。
- 3枚目は未対応です。
> カルーセル１枚目＆２枚目を修正

- src/includes/footer.pug
- src/index.pug
- src/js/privacy.js
- src/privacy.pug
- src/scss/privacy.scss
- webpack.config.js
- フッタのプラポリリンクが機能していること
- プラポリが適切に表示されること
- ヘッダ、フッタのリンクなどおかしな場合があるかもですがひとまずスルーでお願い致しますm(_ _)m
> Add privacy page

- src/scss/home.scss
@sot528 
・カバー画像のサイズを650pxに変更
しました！ご確認よろしくお願いします。
> cover photoのサイズ変更

- src/index.pug
- src/scss/home.scss
- featuresの3つのコンテナを中央揃えにする
- featuresとaboutjapanが同じコンテナに入っているので分ける
> features改善

- src/index.pug
- src/scss/home.scss
@sot528 
・フッターの色をヘッダーに合わせた
・フッターを画面最下部に寄せた
の修正をしましたのでご確認ください！色は暫定なのでお気になさらず。
2点目の画面最下部への寄せをmargin-bottomで実装したのですが、
このやり方が正しいのか自信がないため重点的にレビューいただけると幸いです。
> フッターの色をつけた

- src/scss/home.scss
@sot528 
・ヘッダー・フッター・ICOの色を共通の暗い青色に変更
しました！
上記変更が反映されているかご確認ください。
フォントの色などは別途調整します。
> ヘッダー・フッター・ICOを共通の暗い青色に変更

- src/includes/navbar.pug
- src/js/common.js
@sot528 
ヘッダーのアンカー先の表示ずれを修正しました！
cssの修正だとどうにも全体的にうまく行かなかったので、jsのパラメータを修正しています。
js初修正で正しいか少し不安なのでご確認いただけると幸いです！
> ヘッダーのアンカー先の表示がずれないように修正

- src/includes/footer.pug
- src/scss/home.scss
Please ensure.
- The link of Trello is displayed in the footer.
- You can open and read cards the link by private mode of your browser.
- The design of footer links are not broken from your phone.
Regards.
> Add trello link to footer.

- circle.yml
- package.json
- robots.txt
- src/includes/header.pug
- webpack.config.js
> Adjust dev & staging env.

- src/scss/common.scss
- src/scss/home.scss
@sot528 
- changed footer and heading font color
- changed profile font color
- changed about-japan and feature h4 font color
please check if there is wrong css or bad css coding.
> Adjust colors

- src/scss/home.scss
@sot528 
- expanded email form
- expanded button size and changed color
please check those changes and there is no wrong css coding.
> modified form size and button color&size

- src/includes/navbar.pug
@sot528 please check the points below.
- Roadmap link is correct
- coding is correct
> added roadmap

- src/yaml/en.yml
- src/yaml/zh.yml
This is a little bit emerygency situation, so I merge it by myself.
> removed Bitcoin from ICO information

- src/includes/footer.pug
- src/includes/navbar.pug
- src/index.pug
- src/scss/home.scss
- src/yaml/en.yml
- src/yaml/zh.yml
@sot528 added a header link to our social & mail links
- named the link "meet us"
check if the word is not odd, and coding is correct.
> added meet us on header menu

- circle.yml
- package.json
Revert to: https://github.com/AlisProject/welcome/commits/1.4.0
- diff: https://github.com/AlisProject/welcome/compare/8830ddde2ed72a9e98651c12f5b42842191e971b...1ef753e49c0c708e4b6c4450c0c91ccf5a3e5999
> Revert CI settings for production because of security reason.

- src/includes/navbar.pug
- src/index.pug
- src/scss/common.scss
- src/scss/home.scss
- src/scss/mail-form.scss
- src/yaml/en.yml
- src/yaml/zh.yml
@sot528 
- added button of whitepaper and some text on service-infromation
- changed header link of whitepaper to .pdf link
check if the coding is correct and layout is not collapsed.
> Release whitepaper

- src/includes/navbar.pug
- src/scss/home.scss
- src/yaml/en.yml
@sot528 
sorry that I can't complete this task.
> [WIP] add header link of whitepaper in en and ja

- src/scss/home.scss
@sot528 
I modified smartphone margin on header of language menu. Please check it!
> modified smartphone margin on header menu

- src/includes/footer.pug
@sot528 
- I added youtube on footer. If you click, you can see our videos.
- I removed facebook on footer because our facebook page looks poor
check those change are reflected:)
> removed fb and add youtube on footer

- src/includes/navbar.pug
- src/scss/home.scss
@sot528 
- added twitter and slak icon on navbar
- their color is white
please check the points below
- css coding and naming( Whether I correctly write BEM method or not)
- no layout collapse
> added twitter and slack link on navbar

- src/yaml/en.yml
@sot528 The date in ICO conteta was old date,so I changed it.
> modified text in ICO

- src/includes/navbar.pug
- src/yaml/en.yml
- src/yaml/zh.yml
@sot528 I added link for whitepapaer_zh. please check it :)
> added whitepaper_zh link on navbar

- src/index.pug
@sot528 I changed my twitter name because of marketing, so changed LP twitter link. Please check it :)
> changed yasu's twitter url

- src/includes/footer.pug
@sot528 I changed mailform to telegram because there is no enqury and some users want us to prepare telegram :)
メールフォームを削除し、テレグラムに差し替えました。全くメール問い合わせないのと、テレグラムを要望するユーザが2人ほどいたため。ご確認よろしくお願いします！日本語でコメントできるって素晴らしい！笑
> added telegram

- src/index.pug
- src/mixin/ico_schedule.pug
- src/scss/home.scss
- src/yaml/en.yml
- src/yaml/ja.yml
- src/yaml/zh.yml
> Markup ICO Section

- src/yaml/en.yml
- src/yaml/ja.yml
- src/yaml/zh.yml
@sot528 please check if there is any mistake about ICO information.
> modified ico information

- src/yaml/zh.yml
@erichin check the Chinese is correct 👍
> modified zh.yml

- src/index.pug
> changed Regal to Legal

- src/includes/navbar.pug
- src/scss/home.scss
- src/yaml/en.yml
- src/yaml/ja.yml
- src/yaml/zh.yml
* implememted by using Bootstrap dropdown component
> Add Introduction to Navbar / Change whitepaper link into dropdown

- src/includes/footer.pug
@sot528 I changed telegram to bitcointalk. Please check it.
> changed telegram to bitcointalk

- src/index.pug
- src/yaml/en.yml
- src/yaml/ja.yml
- src/yaml/zh.yml
- yarn.lock
@sot528 I removed some text so as to avoid user's confusion. Please check it :)
> changed ICO part

- src/index.pug
- src/scss/home.scss
> added media logo

- src/yaml/ja.yml
> modified text

- src/index.pug
- src/scss/home.scss
- Add how to buy ALIS token to warning modal.
> Add now to join to warning mordal.

- src/index.pug
> changed job titile name

- src/includes/footer.pug
> changed slack to telegram

- src/yaml/en.yml
@sot528 
I fixed a typo which our community member mentioned.
Regards,
> fixed typo

- src/product.pug
- src/scss/_p-index.scss
- src/yaml/en.yml
- src/yaml/ja.yml
@sot528 please check the two points below.
1. Added bi link to product page
2. Changed kamei's job title
> added bi link and modified kamie's profile

- src/news.pug
- src/yaml/en.yml
- src/yaml/ja.yml
> Mytokenのニュース追加

- src/team.pug
- src/yaml/en.yml
- src/yaml/ja.yml
@sot528 Modified team member's profile url.
> changed profile-link

- src/includes/cover.pug
- src/index.pug
- src/product.pug
- src/scss/_p-index.scss
- src/yaml/ja.yml
> remove list button

- src/news.pug
- src/yaml/en.yml
- src/yaml/ja.yml
> added news

- src/team.pug
- src/yaml/en.yml
- src/yaml/ja.yml
@sot528 Please check the muromachi's profile.
> added muromachi's profile

- src/news.pug
- src/yaml/en.yml
- src/yaml/ja.yml
> Updated the News page

- src/news.pug
- src/yaml/en.yml
- src/yaml/ja.yml
@fiestared @sot528 I updated the News page as requested~!
> BIZ-878 Updated NEWS page.

- src/news.pug
- src/yaml/en.yml
- src/yaml/ja.yml
@fiestared 
Hey Boss, can you check this?
> Updated news page

- src/yaml/ja.yml
@fiestared I changed the contact URL as requested by Mizusawa-san. Could you maybe double check and merge if everything is OK?
> changed contact URL
